### ISSUE TITLE
npm install failure, dependencies conflict

### ISSUE THREAD

**Issue by antonio-fr** [NoRulesJustFeels/hicetnunc-minter-project#1]
On Windows 10 using
NodeJS v16.13.0
npm 8.1.0

There's no versions advised in the Readme, we don't know if that requires Node 14, 16, 17,...
Also a dep lock file would be good for future use.

```
> npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: hen-minter@0.0.1
npm ERR! Found: webpack@5.69.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^5.57.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0" from uglifyjs-webpack-plugin@2.2.0
npm ERR! node_modules/uglifyjs-webpack-plugin
npm ERR!   dev uglifyjs-webpack-plugin@"^2.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by LeonNicholls** [comment]
This doesn't appear to be a NodeJS or npm issue. Looks like something changed in the webpack dependency.
Unfortunately, I don't have time at the moment to find a fix.

**Comment by antonio-fr** [comment]
Can you share you lock file? It may help.

**Comment by antonio-fr** [comment]
Which version of Node are you using?

**Comment by LeonNicholls** [comment]
node: v16.13.2
npm: 8.3.1
[package-lock.zip](https://github.com/NoRulesJustFeels/hicetnunc-minter-project/files/8074039/package-lock.zip)

**Comment by antonio-fr** [comment]
Thanks a lot for your prompt reply. It works like a charm with the lock file. You may make a new commit adding this missing file.

**Comment by LeonNicholls** [comment]
Added lock file.
